language: objective-c
osx_image: xcode10

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=AppReceiptValidator/AppReceiptValidator.xcodeproj
  matrix:
    - DESTINATION="OS=12.0,name=iPhone X"          SCHEME="AppReceiptValidator Demo iOS"
    - DESTINATION="arch=x86_64"                    SCHEME="AppReceiptValidator Demo macOS"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - echo "PROJECT $PROJECT, SCHEME $SCHEME, DESTINATION $DESTINATION"
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
